name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyMuPDF==1.23.8 Pillow==10.1.0 pypdf==3.17.1 reportlab==4.0.7 pyinstaller==6.3.0
    
    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --name "PDF_Password_Remover" pdf_password_remover.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: PDF_Password_Remover_Windows
        path: dist/PDF_Password_Remover.exe
    
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: |
          dist/PDF_Password_Remover.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
